### ISSUE TITLE
Links which request new windows open the default browser

### ISSUE THREAD

**Issue by sammacbeth** [cliqz-oss/cliqz-s#3]
If I click a link which requests a new window (i.e. `target=_blank`) in the WebView, this link is then opened in Edge. We need to override the `NewWindowRequested` behaviour to prevent this behaviour (see https://stackoverflow.com/questions/17432912/how-can-i-disallow-webview-to-open-links-on-the-browser-in-winrt-target-blank)

**Comment by chrmod** [comment]
closing as we are no longer targeting windows platform
